[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FHQ"
version = "0.0.1"
authors = [
  { name="Chang Sun", email="chsun@cern.ch" },
]
description = "FHQ quantization utilities for hls4ml"
readme = "README.md"
requires-python = "==3.10"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]